# DEMOGRAPHIC INFORMATION

In [1]:
import pandas as pd
import numpy as np

In [25]:
demfirst = pd.read_csv('data/dem.csv', index_col="BARCODE2")
demfirst

,BARCODE2_V2,SITE_ID,PATIENT_ID,DTBLDR Date of blood draw,DISEASE2\n1=MS\n2=NMO\n3=ON\n4=TM\n5=ADEM\n6=CIS\nblank = control,DIAGDIS2\n1=Control\n2=Case,VISIT_ID,VISIT_ID.1,ROW_NO,AGE,SEX 1=Male 2=Female,HEIGHT,HTUNIT - Height units 1=IN 2=CM,WEIGHT,WTUNIT - Weight units 1=LB 2=KG,DOMHAN - Dominant hand 1=Right 2=Left 3=Ambidextrous 4=Don't know
BARCODE2,,,,,,,,,,,,,,,,
AC000003,AL100611,81,21,4/9/07,1.0,2.0,0,0,0,61.0,1.0,71.0,1.0,200.0,1.0,2.0
AC000005,AL100388,1,22,10/18/06,1.0,2.0,0,0,0,54.0,2.0,66.0,1.0,206.0,1.0,1.0
AC000006,NaN,1,182,10/23/07,NaN,1.0,0,0,0,33.0,2.0,64.0,1.0,225.0,1.0,1.0
AC000007,NaN,80,70,3/17/08,NaN,1.0,0,0,0,45.0,1.0,70.5,1.0,176.0,1.0,2.0
AC000009,NaN,78,325,4/4/07,4.0,2.0,0,0,0,54.0,2.0,65.5,1.0,130.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
PC001059,NaN,82,552,10/23/12,NaN,1.0,0,0,0,7.0,1.0,52.0,1.0,60.0,1.0,1.0
PC001064,NaN,82,550,10/23/12,NaN,1.0,0,0,0,15.0,2.0,64.0,1.0,130.0,1.0,1.0
PC001065,NaN,82,558,10/23/12,NaN,1.0,0,0,0,17.0,2.0,65.0,1.0,108.0,1.0,1.0
PC001069,NaN,1,613,12/12/12,NaN,1.0,0,0,0,16.0,2.0,69.0,1.0,133.0,1.0,2.0
PC001070,NaN,82,644,10/23/12,NaN,1.0,0,0,0,11.0,2.0,60.0,1.0,76.0,1.0,1.0

In [26]:
# import pandas_profiling
# profile = demfirst.profile_report(title='Demographic Profiling')
# profile.to_file(output_file='demographic-profiling.html')

Drop ['BARCODE2_V2', 'SITE_ID', 'PATIENT_ID', 'DTBLDR  Date of blood draw', 'VISIT_ID', 'VISIT_ID.1', 'ROW_NO']
Rename remaining columns: disease, diag_dis, age, sex, ht,ht_units, wt, wt_units, dom_hand
Convert values: sex, ht_cm, wt_kg, dom_hand, diag_dis, disease
These columns need to be mapped from numbers to values
Drop unused columns: ['ht', 'ht_units', 'wt', 'wt_units']
Profile to check, then pickle to dem.pkl

In [27]:
dem2 = demfirst.drop(columns=['BARCODE2_V2', 'SITE_ID', 'PATIENT_ID', 'DTBLDR  Date of blood draw', 'VISIT_ID', 'VISIT_ID.1', 'ROW_NO'])

In [28]:
colnames = ['disease', 'diag_dis', 'age', 'sex', 'ht', 'ht_units', 'wt', 'wt_units', 'dom_hand']
dem2.columns = colnames
dem2

,disease,diag_dis,age,sex,ht,ht_units,wt,wt_units,dom_hand
BARCODE2,,,,,,,,,
AC000003,1.0,2.0,61.0,1.0,71.0,1.0,200.0,1.0,2.0
AC000005,1.0,2.0,54.0,2.0,66.0,1.0,206.0,1.0,1.0
AC000006,NaN,1.0,33.0,2.0,64.0,1.0,225.0,1.0,1.0
AC000007,NaN,1.0,45.0,1.0,70.5,1.0,176.0,1.0,2.0
AC000009,4.0,2.0,54.0,2.0,65.5,1.0,130.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...
PC001059,NaN,1.0,7.0,1.0,52.0,1.0,60.0,1.0,1.0
PC001064,NaN,1.0,15.0,2.0,64.0,1.0,130.0,1.0,1.0
PC001065,NaN,1.0,17.0,2.0,65.0,1.0,108.0,1.0,1.0
PC001069,NaN,1.0,16.0,2.0,69.0,1.0,133.0,1.0,2.0
PC001070,NaN,1.0,11.0,2.0,60.0,1.0,76.0,1.0,1.0

In [29]:
disease = {1.0:'MS', 2.0:'NMO', 3.0:'ON', 4.0:'TM', 5.0:'ADEM', 6.0:'CIS', np.nan:'CONTROL'}
dem2['disease_mapped'] = dem2['disease'].map(disease)
diag = {1.0:'CONTROL', 2.0:'CASE'}
dem2['diag_mapped'] = dem2['diag_dis'].map(diag)
hand = {1.0:'RIGHT', 2.0:'LEFT', 3.0:'AMBIDEXTROUS', 4.0:'UNKNOWN'}
dem2['hand_mapped'] = dem2['dom_hand'].map(hand)
sex = {1.0:'MALE', 2.0:'FEMALE'}
dem2['sex_mapped'] = dem2['sex'].map(sex)
dem2

,disease,diag_dis,age,sex,ht,ht_units,wt,wt_units,dom_hand,disease_mapped,diag_mapped,hand_mapped,sex_mapped
BARCODE2,,,,,,,,,,,,,
AC000003,1.0,2.0,61.0,1.0,71.0,1.0,200.0,1.0,2.0,MS,CASE,LEFT,MALE
AC000005,1.0,2.0,54.0,2.0,66.0,1.0,206.0,1.0,1.0,MS,CASE,RIGHT,FEMALE
AC000006,NaN,1.0,33.0,2.0,64.0,1.0,225.0,1.0,1.0,CONTROL,CONTROL,RIGHT,FEMALE
AC000007,NaN,1.0,45.0,1.0,70.5,1.0,176.0,1.0,2.0,CONTROL,CONTROL,LEFT,MALE
AC000009,4.0,2.0,54.0,2.0,65.5,1.0,130.0,1.0,1.0,TM,CASE,RIGHT,FEMALE
...,...,...,...,...,...,...,...,...,...,...,...,...,...
PC001059,NaN,1.0,7.0,1.0,52.0,1.0,60.0,1.0,1.0,CONTROL,CONTROL,RIGHT,MALE
PC001064,NaN,1.0,15.0,2.0,64.0,1.0,130.0,1.0,1.0,CONTROL,CONTROL,RIGHT,FEMALE
PC001065,NaN,1.0,17.0,2.0,65.0,1.0,108.0,1.0,1.0,CONTROL,CONTROL,RIGHT,FEMALE
PC001069,NaN,1.0,16.0,2.0,69.0,1.0,133.0,1.0,2.0,CONTROL,CONTROL,LEFT,FEMALE
PC001070,NaN,1.0,11.0,2.0,60.0,1.0,76.0,1.0,1.0,CONTROL,CONTROL,RIGHT,FEMALE

In [30]:
# listcomprension here
# for w,u in zip(dem2['wt'], dem2['wt_units']):
#     if u == 1.0:
dem2['wt_kg'] = [(w * 0.45359237) if u == 1.0 else u for w,u in zip(dem2['wt'], dem2['wt_units'])]
dem2['ht_cm'] = [(h * 2.54) if u == 1.0 else u for h,u in zip(dem2['ht'], dem2['ht_units'])]
dem2

,disease,diag_dis,age,sex,ht,ht_units,wt,wt_units,dom_hand,disease_mapped,diag_mapped,hand_mapped,sex_mapped,wt_kg,ht_cm
BARCODE2,,,,,,,,,,,,,,,
AC000003,1.0,2.0,61.0,1.0,71.0,1.0,200.0,1.0,2.0,MS,CASE,LEFT,MALE,90.718474,180.34
AC000005,1.0,2.0,54.0,2.0,66.0,1.0,206.0,1.0,1.0,MS,CASE,RIGHT,FEMALE,93.440028,167.64
AC000006,NaN,1.0,33.0,2.0,64.0,1.0,225.0,1.0,1.0,CONTROL,CONTROL,RIGHT,FEMALE,102.058283,162.56
AC000007,NaN,1.0,45.0,1.0,70.5,1.0,176.0,1.0,2.0,CONTROL,CONTROL,LEFT,MALE,79.832257,179.07
AC000009,4.0,2.0,54.0,2.0,65.5,1.0,130.0,1.0,1.0,TM,CASE,RIGHT,FEMALE,58.967008,166.37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
PC001059,NaN,1.0,7.0,1.0,52.0,1.0,60.0,1.0,1.0,CONTROL,CONTROL,RIGHT,MALE,27.215542,132.08
PC001064,NaN,1.0,15.0,2.0,64.0,1.0,130.0,1.0,1.0,CONTROL,CONTROL,RIGHT,FEMALE,58.967008,162.56
PC001065,NaN,1.0,17.0,2.0,65.0,1.0,108.0,1.0,1.0,CONTROL,CONTROL,RIGHT,FEMALE,48.987976,165.10
PC001069,NaN,1.0,16.0,2.0,69.0,1.0,133.0,1.0,2.0,CONTROL,CONTROL,LEFT,FEMALE,60.327785,175.26
PC001070,NaN,1.0,11.0,2.0,60.0,1.0,76.0,1.0,1.0,CONTROL,CONTROL,RIGHT,FEMALE,34.473020,152.40

In [31]:
dem3 = dem2.drop(columns=colnames
                )
dem3

         disease_mapped diag_mapped hand_mapped sex_mapped       wt_kg   ht_cm
BARCODE2
AC000003             MS        CASE        LEFT       MALE   90.718474  180.34
AC000005             MS        CASE       RIGHT     FEMALE   93.440028  167.64
AC000006        CONTROL     CONTROL       RIGHT     FEMALE  102.058283  162.56
AC000007        CONTROL     CONTROL        LEFT       MALE   79.832257  179.07
AC000009             TM        CASE       RIGHT     FEMALE   58.967008  166.37
...                 ...         ...         ...        ...         ...     ...
PC001059        CONTROL     CONTROL       RIGHT       MALE   27.215542  132.08
PC001064        CONTROL     CONTROL       RIGHT     FEMALE   58.967008  162.56
PC001065        CONTROL     CONTROL       RIGHT     FEMALE   48.987976  165.10
PC001069        CONTROL     CONTROL        LEFT     FEMALE   60.327785  175.26
PC001070        CONTROL     CONTROL       RIGHT     FEMALE   34.473020  152.40

[3228 rows x 6 columns]

In [32]:
dem3.columns = ['disease', 'diag_dis', 'dom_hand', 'sex', 'wt_kg', 'ht_cm']
dem3

          disease diag_dis dom_hand     sex       wt_kg   ht_cm
BARCODE2
AC000003       MS     CASE     LEFT    MALE   90.718474  180.34
AC000005       MS     CASE    RIGHT  FEMALE   93.440028  167.64
AC000006  CONTROL  CONTROL    RIGHT  FEMALE  102.058283  162.56
AC000007  CONTROL  CONTROL     LEFT    MALE   79.832257  179.07
AC000009       TM     CASE    RIGHT  FEMALE   58.967008  166.37
...           ...      ...      ...     ...         ...     ...
PC001059  CONTROL  CONTROL    RIGHT    MALE   27.215542  132.08
PC001064  CONTROL  CONTROL    RIGHT  FEMALE   58.967008  162.56
PC001065  CONTROL  CONTROL    RIGHT  FEMALE   48.987976  165.10
PC001069  CONTROL  CONTROL     LEFT  FEMALE   60.327785  175.26
PC001070  CONTROL  CONTROL    RIGHT  FEMALE   34.473020  152.40

[3228 rows x 6 columns]

In [35]:
dem = dem3
dem.to_pickle('pkl/dem.pkl')

OSError: Cannot save file into a non-existent directory: 'pkl'