# DEM

In [1]:
import pandas as pd

In [9]:
dem = pd.read_csv('data/dem.csv', index_col="BARCODE2")
dem

,BARCODE2_V2,SITE_ID,PATIENT_ID,DTBLDR Date of blood draw,DISEASE2\n1=MS\n2=NMO\n3=ON\n4=TM\n5=ADEM\n6=CIS\nblank = control,DIAGDIS2\n1=Control\n2=Case,VISIT_ID,VISIT_ID.1,ROW_NO,AGE,SEX 1=Male 2=Female,HEIGHT,HTUNIT - Height units 1=IN 2=CM,WEIGHT,WTUNIT - Weight units 1=LB 2=KG,DOMHAN - Dominant hand 1=Right 2=Left 3=Ambidextrous 4=Don't know
BARCODE2,,,,,,,,,,,,,,,,
AC000003,AL100611,81,21,4/9/07,1.0,2.0,0,0,0,61.0,1.0,71.0,1.0,200.0,1.0,2.0
AC000005,AL100388,1,22,10/18/06,1.0,2.0,0,0,0,54.0,2.0,66.0,1.0,206.0,1.0,1.0
AC000006,NaN,1,182,10/23/07,NaN,1.0,0,0,0,33.0,2.0,64.0,1.0,225.0,1.0,1.0
AC000007,NaN,80,70,3/17/08,NaN,1.0,0,0,0,45.0,1.0,70.5,1.0,176.0,1.0,2.0
AC000009,NaN,78,325,4/4/07,4.0,2.0,0,0,0,54.0,2.0,65.5,1.0,130.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
PC001059,NaN,82,552,10/23/12,NaN,1.0,0,0,0,7.0,1.0,52.0,1.0,60.0,1.0,1.0
PC001064,NaN,82,550,10/23/12,NaN,1.0,0,0,0,15.0,2.0,64.0,1.0,130.0,1.0,1.0
PC001065,NaN,82,558,10/23/12,NaN,1.0,0,0,0,17.0,2.0,65.0,1.0,108.0,1.0,1.0
PC001069,NaN,1,613,12/12/12,NaN,1.0,0,0,0,16.0,2.0,69.0,1.0,133.0,1.0,2.0
PC001070,NaN,82,644,10/23/12,NaN,1.0,0,0,0,11.0,2.0,60.0,1.0,76.0,1.0,1.0